name: venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - nodejs=22
  - pip
  - pip:
    
    - fastapi==0.111.0 # server
    - uvicorn==0.30.1 # web-serber ASGI
    - sqlalchemy==2.0.30 # ORM
    - asyncpg==0.29.0 # DB driver postgralSQL
    - greenlet==3.0.3 # SQLAlchemy async 
    - python-dotenv==1.0.1 # project Config
    - aiomqtt==2.3.0 # mqtt
    - google-generativeai==0.8.3 # Gemini LLM API
    - httpx==0.28.1 # Ollama local LLM 호출
    - pydantic==2.7.4 # data validation
    - eval_type_backport==0.2.0 # `date | None` 등 PEP 604 타입 평가 백포트
    - opencv-python==4.10.0.84 # camera, image processing
    - loguru==0.7.3 # logging
    - ultralytics ==8.4.38 # 욜로 