name: venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    
    - fastapi==0.111.0 # 서버 
    - uvicorn==0.30.1 # 웹서버 ASGI
    - sqlalchemy==2.0.30 # ORM
    - aiomysql==0.2.0 # DB 드라이버
    - boto3==1.34.100 # AWS 연결 
    - python-dotenv==1.0.1 # 보안 고나련 